// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6vDXEFD97Rfg_LYip-r4-fR1unHyU0M',
    appId: '1:581507658371:web:be365836533eb733b7a1b6',
    messagingSenderId: '581507658371',
    projectId: 'pet-app-fccae',
    authDomain: 'pet-app-fccae.firebaseapp.com',
    storageBucket: 'pet-app-fccae.appspot.com',
    measurementId: 'G-Q2NZLHJJ8V',
  );

  // appId do cliente Android `com.kayque.pets` (google-services.json). O
  // anterior (…90ea1e66…) era do `com.example.pet_app` e deixaria o app
  // conectando como outro cliente do mesmo projeto.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Zpf4NcAga2GmRHfvyWUHJNNQZasCS_A',
    appId: '1:581507658371:android:2120a5c2af99d455b7a1b6',
    messagingSenderId: '581507658371',
    projectId: 'pet-app-fccae',
    storageBucket: 'pet-app-fccae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAhYDhVEXTcrcE3Lvb-Tw23n1s35K0xI',
    appId: '1:581507658371:ios:b0afbcd4b3a93170b7a1b6',
    messagingSenderId: '581507658371',
    projectId: 'pet-app-fccae',
    storageBucket: 'pet-app-fccae.appspot.com',
    iosClientId: '581507658371-ugopko3bglbf3pt68h0otttn23mpn1q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAhYDhVEXTcrcE3Lvb-Tw23n1s35K0xI',
    appId: '1:581507658371:ios:b0afbcd4b3a93170b7a1b6',
    messagingSenderId: '581507658371',
    projectId: 'pet-app-fccae',
    storageBucket: 'pet-app-fccae.appspot.com',
    iosClientId: '581507658371-ugopko3bglbf3pt68h0otttn23mpn1q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );
}
